"""
Email service for sending generated content via SMTP
"""
import smtplib
import ssl
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders
import os
from typing import Dict, Any, List, Optional
from jinja2 import Template
import asyncio
import aiosmtplib

from app.config import settings


class EmailService:
    """Service for sending emails with generated content"""
    
    def __init__(self):
        self.smtp_host = settings.smtp_host
        self.smtp_port = settings.smtp_port
        self.smtp_username = settings.smtp_username
        self.smtp_password = settings.smtp_password
        self.from_email = settings.from_email
    
    def _get_smtp_config(self, user_settings: Optional[Dict[str, Any]] = None) -> Dict[str, str]:
        """Get SMTP configuration from user settings or global config"""
        if user_settings and user_settings.get("smtp_settings"):
            smtp_settings = user_settings["smtp_settings"]
            return {
                "host": smtp_settings.get("host", self.smtp_host),
                "port": int(smtp_settings.get("port", self.smtp_port)),
                "username": smtp_settings.get("username", self.smtp_username),
                "password": smtp_settings.get("password", self.smtp_password),
                "from_email": smtp_settings.get("from_email", self.from_email)
            }
        else:
            return {
                "host": self.smtp_host,
                "port": self.smtp_port,
                "username": self.smtp_username,
                "password": self.smtp_password,
                "from_email": self.from_email
            }
    
    def _create_html_template(self) -> str:
        """Create HTML email template"""
        return """
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ subject }}</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
        }
        .header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 20px;
            border-radius: 8px 8px 0 0;
            text-align: center;
        }
        .content {
            background: #f8f9fa;
            padding: 30px;
            border-radius: 0 0 8px 8px;
        }
        .article-content {
            background: white;
            padding: 25px;
            border-radius: 8px;
            margin: 20px 0;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
        .images {
            margin: 20px 0;
        }
        .image-item {
            margin: 10px 0;
            padding: 10px;
            background: white;
            border-radius: 4px;
            border-left: 4px solid #667eea;
        }
        .footer {
            text-align: center;
            margin-top: 30px;
            padding: 20px;
            color: #666;
            font-size: 14px;
            border-top: 1px solid #ddd;
        }
        h1, h2, h3 { color: #2c3e50; }
        a { color: #667eea; text-decoration: none; }
        a:hover { text-decoration: underline; }
        .meta { color: #666; font-size: 14px; margin-bottom: 20px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ subject }}</h1>
        <p>Generated by Scratch Automation App</p>
    </div>
    
    <div class="content">
        <div class="meta">
            <strong>Topic:</strong> {{ topic }}<br>
            <strong>Generated:</strong> {{ generated_at }}<br>
            {% if task_id %}<strong>Task ID:</strong> {{ task_id }}{% endif %}
        </div>
        
        <div class="article-content">
            {{ content | safe }}
        </div>
        
        {% if images %}
        <div class="images">
            <h3>Suggested Images:</h3>
            {% for image in images %}
            <div class="image-item">
                <strong>Image {{ loop.index }}:</strong><br>
                <a href="{{ image.url }}" target="_blank">{{ image.url }}</a><br>
                <small>{{ image.attribution }}</small>
            </div>
            {% endfor %}
        </div>
        {% endif %}
    </div>
    
    <div class="footer">
        <p>This content was automatically generated by Scratch Automation App.</p>
        <p>If you have any questions, please contact the sender.</p>
    </div>
</body>
</html>
        """
    
    async def send_email(
        self,
        to_email: str,
        subject: str,
        content: str,
        topic: str = "",
        images: Optional[List[Dict[str, Any]]] = None,
        task_id: Optional[str] = None,
        user_settings: Optional[Dict[str, Any]] = None,
        attachments: Optional[List[str]] = None
    ) -> Dict[str, Any]:
        """Send email with generated content"""
        
        try:
            smtp_config = self._get_smtp_config(user_settings)
            
            # Validate SMTP configuration
            if not all([smtp_config["host"], smtp_config["username"], smtp_config["password"], smtp_config["from_email"]]):
                return {
                    "success": False,
                    "error": "SMTP configuration incomplete. Please check your email settings."
                }
            
            # Create message
            msg = MIMEMultipart('alternative')
            msg['Subject'] = subject
            msg['From'] = smtp_config["from_email"]
            msg['To'] = to_email
            
            # Create plain text version
            text_content = f"""
{subject}

Topic: {topic}
Generated by: Scratch Automation App
Task ID: {task_id or 'N/A'}

Content:
{content}

---
This content was automatically generated by Scratch Automation App.
            """
            
            # Create HTML version
            html_template = Template(self._create_html_template())
            html_content = html_template.render(
                subject=subject,
                topic=topic,
                content=content.replace('\n', '<br>'),
                images=images or [],
                task_id=task_id,
                generated_at=f"{asyncio.get_event_loop().time()}"
            )
            
            # Attach both versions
            text_part = MIMEText(text_content, 'plain')
            html_part = MIMEText(html_content, 'html')
            
            msg.attach(text_part)
            msg.attach(html_part)
            
            # Add attachments if provided
            if attachments:
                for file_path in attachments:
                    if os.path.exists(file_path):
                        with open(file_path, "rb") as attachment:
                            part = MIMEBase('application', 'octet-stream')
                            part.set_payload(attachment.read())
                        
                        encoders.encode_base64(part)
                        part.add_header(
                            'Content-Disposition',
                            f'attachment; filename= {os.path.basename(file_path)}'
                        )
                        msg.attach(part)
            
            # Send email using aiosmtplib for async support
            await aiosmtplib.send(
                msg,
                hostname=smtp_config["host"],
                port=smtp_config["port"],
                start_tls=True,
                username=smtp_config["username"],
                password=smtp_config["password"],
                timeout=30
            )
            
            return {
                "success": True,
                "message": f"Email sent successfully to {to_email}",
                "to_email": to_email,
                "subject": subject
            }
            
        except aiosmtplib.SMTPAuthenticationError:
            return {
                "success": False,
                "error": "SMTP authentication failed. Please check your email credentials."
            }
        except aiosmtplib.SMTPRecipientsRefused:
            return {
                "success": False,
                "error": f"Recipient email address rejected: {to_email}"
            }
        except aiosmtplib.SMTPException as e:
            return {
                "success": False,
                "error": f"SMTP error: {str(e)}"
            }
        except Exception as e:
            return {
                "success": False,
                "error": f"Failed to send email: {str(e)}"
            }
    
    async def test_smtp_connection(self, user_settings: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        """Test SMTP connection and authentication"""
        
        try:
            smtp_config = self._get_smtp_config(user_settings)
            
            # Validate configuration
            if not all([smtp_config["host"], smtp_config["username"], smtp_config["password"]]):
                return {
                    "success": False,
                    "error": "SMTP configuration incomplete"
                }
            
            # Test connection
            await aiosmtplib.connect(
                hostname=smtp_config["host"],
                port=smtp_config["port"],
                start_tls=True,
                username=smtp_config["username"],
                password=smtp_config["password"],
                timeout=10
            )
            
            return {
                "success": True,
                "message": "SMTP connection successful"
            }
            
        except aiosmtplib.SMTPAuthenticationError:
            return {
                "success": False,
                "error": "SMTP authentication failed"
            }
        except Exception as e:
            return {
                "success": False,
                "error": f"SMTP connection failed: {str(e)}"
            }


# Global email service instance
email_service = EmailService()
